config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    resources :personal_orders
  end
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'orders#index'
  get '/personal_orders/add_to/:id', to: 'personal_orders#show'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  match 'orders/:id/release', to: 'orders#update_release', via: :patch
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :restaurant, presence: true
  validates :menu_url, presence: true
  validates :tax, presence: true, :numericality => { only_integer: true }
  validates :tip, presence: true, :numericality => { only_integer: true }
  has_many :personal_orders, :dependent => :destroy
  belongs_to :user
end

app/models/personal_order.rb
class PersonalOrder < ApplicationRecord
  belongs_to :order
  validates :price, :presence => true, numericality: true
  validates :items, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :orders, :dependent => :destroy
  has_many :personal_orders, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  helper_method :current_user

  def authenticate_user
    redirect_to login_path unless current_user
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user

  def index
    @orders = Order.all.order(created_at: :desc)
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.ordered = false
    # adjust the prices
    # @modified_p_orders = @order.personal_orders
    # @modified_p_orders.each do |p_order|
    #   p_order.price = p_order.price * (1 + (@order.tax.to_f + @order.tip.to_f) / 100)
    # end
    if @order.save
      # If save succeeds, redirect to the index action
      flash[:notice] = "Your order was created successfully."
      redirect_to(order_path(@order))
    else
      # If save fails, redisplay the form so user can fix problems
      flash[:notice] = "All fields must be filled out"
      render('new')
    end
  end

  def update_release
    @order = Order.find(params[:id])
    @order.ordered = true
    if @order.save
      flash[:notice] = "The order has been confirmed."
      redirect_to(order_path(@order))
    else
      flash[:notice] = "Something happened and the order was not confirmed."
    end
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "Your order info has been changed."
      redirect_to order_path(@order)
    else
      flash[:notice] = @order.errors.full_messages
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    flash[:notice] = "Cancelled your order!"
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:restaurant, :menu_url, :tip, :tax)
  end

end

app/controllers/personal_orders_controller.rb
class PersonalOrdersController < ApplicationController

  def index
    redirect_to order_path(params[:order_id])
  end

  def new
    @personal_order = PersonalOrder.new
    @parent_order = get_parent_order
  end

  def create
    @parent_order = get_parent_order
    @personal_order = PersonalOrder.new(personal_order_params)
    @personal_order.order_id = params[:order_id]
    @personal_order.user_id = current_user.id
    @personal_order.name = current_user.name
    if !@personal_order.valid?
      flash[:notice] = @personal_order.errors.full_messages;
      render :new
    else
      # the following is an adjustment on the price
      @personal_order.price = (@personal_order.price).round(2)
      if @personal_order.save
        flash[:notice] = 'saved!'
        redirect_to order_path(:id => params[:order_id])
      else
        flash[:notice] = @personal_order.errors.full_messages;
        render :new
      end
    end
  end

  def show
    @personal_order = PersonalOrder.new
    @order_ref = params[:id]
  end

  def destroy
    @remove_order = PersonalOrder.find(params[:order_id])
    @remove_order.destroy
    flash[:notice] = "Cancelled your order!"
    redirect_to order_path(:id => params[:id])
  end

  private

  def personal_order_params
    params.require(:personal_order).permit(:name, :price, :items)
  end

  def get_parent_order
    Order.find(params[:order_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In"
      redirect_to orders_path
    else
      flash[:notice] = "Sorry, something you inputted didn't match up"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to login_path
  end

  def edit
  end

  def update
    if current_user.update(required_user_params)
      redirect_to orders_path
    else
      flash[:notice] = "Whoops you're probably missing a field"
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(required_user_params)
    if @user.save
      flash[:notice] = "Great!"
      redirect_to login_path
    else
      flash[:notice] = "Error"
      render :new
    end
  end

  private

  def required_user_params
    params.require(:user).permit(:email, :name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/personal_orders_helper.rb
module PersonalOrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orderfood</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='auth-nav'>
      <ul class="nav">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'User Info', edit_user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Out', logout_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <% if notice %>
        <div class="container">
          <div class="alert alert-info alert-dismissible show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong><%= notice %></strong>
          </div>
        </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/edit.html.erb
<div id="edit-form">
  <%= form_for @order, url: order_path(@order) do |f| %>
    <div>
      Restaurant Name: <br>
      <%= f.text_field :restaurant, :value => @order.restaurant %>
    </div>
    <div>
      Menu URL: <br>
      <%= f.text_field :menu_url, value: @order.menu_url %>
    </div>
    <div>
      Tip Percentage:
      <%= f.number_field :tip, value: @order.tip %>
    </div>
    <div>
      Tax Percentage:
      <%= f.number_field :tax, value: @order.tax %>
    </div>
    <%= f.submit "Update", :class => "submit" %>
  <% end %>
</div>

app/views/orders/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">All the orders, ever!</h1>
    <p class="lead">Take a look at all the orders below, and feel free to make your own.</p>
  </div>
</div>
<div style="display:flex; justify-content: flex-end; margin-top: 30px; margin-bottom: 30px">
  <%= link_to 'Make new order', new_order_path, class: "btn btn-info btn-lrg active" %>
</div>
<div>
<table class="table table-striped table-bordered">
  <tr>
    <th></th>
    <th>Restaurant</th>
    <th>Who's Ordering</th>
    <th onclick="order()">Status: <span id="status-indicator">All</span></th>
    <th></th>
  </tr>
    <% @orders.each_with_index do |order, i| %>
      <tr>
        <td><%= i + 1 %> </td>
        <td><%= order.restaurant %></td>
        <td>
          <% if order.user_id && User.find(order.user_id) %>
            <%= User.find(order.user_id).name %>
          <% end %>
        </td>
        <td>
          <% if order.ordered %>
            <div class="status-issue">
              Closed
            </div>
          <% else %>
            <div class="status-success">
              Open
            </div>
          <% end %>
        </td>
        <td>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Action
            </button>
            <div class="dropdown-menu">
              <%= link_to 'Show', order_path(:id => order.id), class: "dropdown-item" %>
              <% if order.user_id && order.user_id == current_user.id %>
                <%= link_to 'Edit', order_path(:id => order.id), class: "dropdown-item" %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<script>
 var statusArray = ["All", "Closed", "Open"];
 var currentStatus = "All";
 var prevStatus;
 var statusIndicator = document.getElementById("status-indicator");
 function order() {
   prevStatus = statusArray.shift();
   currentStatus = statusArray[0];
   statusArray.push(prevStatus);
   statusIndicator.textContent = currentStatus;
  };
</script>

app/views/orders/new.html.erb
<h1> Need a form here </h1>

<div>
  <%= form_for @order, url: orders_path do |f| %>
    <div>
      Restaurant Name: <br>
      <%= f.text_field :restaurant %>
    </div>
    <div>
      Menu URL: <br>
      <%= f.text_field :menu_url %>
    </div>
    <div>
      Tip Percentage:
      <%= f.number_field :tip %>
    </div>
    <div>
      Tax Percentage:
      <%= f.number_field :tax %>
    </div>
    <%= f.submit "Create", :class => "submit" %>
  <% end %>
</div>

app/views/orders/show.html.erb
<h3>I'm ordering from <%= @order.restaurant %>. </h3>
<h4> A link to the menu can be found here: <%= @order.menu_url %> </h4>
<h4> Tax: <%= @order.tax ? number_to_percentage(@order.tax, precision: 0) : '0%' %></h4>
<h4> Tip: <%= @order.tip ? number_to_percentage(@order.tip, precision: 0) : '0%' %></h4>

<p class="bg-info">
  <h4>All current orders:</h4>
</p>

<div>
  <table class="table table-striped table-bordered">
    <tr>
      <th></th>
      <th>Name</th>
      <th>Items</th>
      <th>Price</th>
      <th>Amount Owing </th>
      <% unless @order.ordered %>
        <th>Actions</th>
      <% end %>
    </tr>
    <% @order.personal_orders.each_with_index do |p_order, i| %>
    <tr>
      <td><%= i + 1 %> </td>
      <td><%= p_order.name %></td>
      <td><%= p_order.items %></td>
      <td><%= number_to_currency(p_order.price) %></td>
      <td><%= number_to_currency(p_order.price * (1 + (@order.tax.to_f + @order.tip.to_f) / 100)) %> </td>
      <td>
        <% if current_user.id == p_order.user_id && !@order.ordered %>
          <%= link_to 'Cancel Order', order_personal_order_path(p_order),
            data: {:confirm => 'Are you sure?'}, :method => :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td></td><td></td><td></td>
    <td>Subtotal: <%= number_to_currency(@order.personal_orders.sum("price")) %></td>
    <td>Total: <%= number_to_currency((1 + ((@order.tax.to_f + @order.tip.to_f) / 100)) * @order.personal_orders.sum("price")) %></td>
  </tr>
  </table>
</div>
<div style="margin-top: 20px; display: flex; justify-content: space-between">
  <% if !@order.ordered %>
    <div>
      <%= link_to 'Get your order in!', new_order_personal_order_path(:order_id => @order.id), class: "btn btn-primary btn-med active" %>
    </div>
    <% if current_user.id == @order.user_id %>
    <div>
      <%= link_to 'Make Order.', "/orders/#{@order.id}/release", :method => :patch, data: {:confirm => "Make the order?"},
        class: "btn btn-info btn-med active" %>
      <%= link_to 'Edit Order.', edit_order_path(@order), :method => :get,
        class: "btn btn-warning btn-med active" %>
      <%= link_to 'Remove Order.', order_path(@order), :method => :delete, data: {:confirm => 'Are you sure?'},
        class: "btn btn-danger btn-med active" %>
    </div>
    <% end %>
  <% else %>
    Order has been made!
  <% end %>
</div>
<div style="margin-top: 20px">
  &#9664;<%= link_to 'Back to all orders', orders_path %>
</div>

app/views/personal_orders/index.html.erb
Filler

app/views/personal_orders/new.html.erb
<% if @parent_order.ordered %>
  <br>
  This order has already been made, sorry!
  <br><br>
  <%= link_to 'Back to the order', order_path(@parent_order) %>
<% else %>
  <div class="rcorners2">
    <%= form_for @personal_order, url: order_personal_orders_path do |f| %>
      You are going to add an order for: <%= @parent_order.restaurant %>
      <div class="form-group">
        Your name: <%= current_user.name %>
      </div>
      <div class="form-group">
        What would you like?: <br>
        <%= f.text_field :items %>
      </div>
      <div class="form-group">
        Price: <br>
        <%= f.text_field :price %>
      </div>
      <%= f.submit "Create", :class => "submit" %>
  </div>
  <% end %>
<% end %>

app/views/personal_orders/show.html.erb
Add your personal order for <%= @order_ref %>
<%= form_for @personal_order, url: order_personal_orders_path do |f| %>
  <div>
    Your Name: <br>
    <%= f.text_field :name %>
  </div>
  <div>
    What would you like?: <br>
    <%= f.text_field :items %>
  </div>
  <div>
    Price: <br>
    <%= f.text_field :price %>
  </div>
  <%= f.submit "Create", :class => "submit" %>
<% end %>

app/views/users/edit.html.erb
<h4>Edit</h4>
<%= form_for(current_user) do |f| %>
  <div>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
Sign Up:
<%= form_for(@user) do |f| %>
  <%if @user.errors.any? %>
    <p> There were some errors with your form </p>
  <% end %>
  <div>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  </div>
<% end %>